customLibraries:
  array:
    - object:
        version: 4.17.21
        language: javascript
        variable: _
        codeString: |
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: lodash
    - object:
        version: 2.1.0
        language: javascript
        variable: numbro
        codeString: |
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: numbro
    - object:
        version: 5.3.2
        language: javascript
        variable: Papa
        codeString: |
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: papaparse
    - object:
        version: 0.5.23
        language: javascript
        variable: moment
        codeString: |
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: moment-timezone
    - object:
        version: 3.4.0
        language: javascript
        variable: uuid
        codeString: |
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: uuid
name: Workflow - Blake R - Jul 2, 2024 4:51 PM
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: |
          // lodash
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // numbro
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // papaparse
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // moment-timezone
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // uuid
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
version: 43.0.9
workflowId: 8e579d3e-2d54-4370-a708-0b4270dc9fbd
description: null
workflowTemplate:
  version: 3.52.14
