version: 43.0.9
pageUuid: 20f98918-f13a-11ee-8b55-d36e002407e3
appTemplate:
  notificationsSettings:
    object:
      globalQueryShowFailureToast: true
      globalQueryShowSuccessToast: true
      globalQueryToastDuration: 4.5
  shortlink: false
  version: 3.52.1
  experimentalDataTabEnabled: true
